In [27]:
import pandas as pd

In [28]:
df = pd.DataFrame({"name":["asad","asia","adil"],"age":[21,22.5,23] })
print(df)

   name   age
0  asad  21.0
1  asia  22.5
2  adil  23.0

In [29]:
df["name"]
df["age"]

0    21.0
1    22.5
2    23.0
Name: age, dtype: float64

In [30]:
df1 = pd.read_csv("Housing.csv")
print(df1)

        price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no
1    12250000  8960         4          4        4      yes        no       no
2    12250000  9960         3          2        2      yes        no      yes
3    12215000  7500         4          2        2      yes        no      yes
4    11410000  7420         4          1        2      yes       yes      yes
..        ...   ...       ...        ...      ...      ...       ...      ...
540   1820000  3000         2          1        1      yes        no      yes
541   1767150  2400         3          1        1       no        no       no
542   1750000  3620         2          1        1      yes        no       no
543   1750000  2910         3          1        1       no        no       no
544   1750000  3850         3          1        2      yes        no       no

    hotwaterheating airconditioning  parking prefarea furnishingstatus
0                no             yes        2      yes        furnished
1                no             yes        3       no        furnished
2                no              no        2      yes   semi-furnished
3                no             yes        3      yes        furnished
4                no             yes        2       no        furnished
..              ...             ...      ...      ...              ...
540              no              no        2       no      unfurnished
541              no              no        0       no   semi-furnished
542              no              no        0       no      unfurnished
543              no              no        0       no        furnished
544              no              no        0       no      unfurnished

[545 rows x 13 columns]

In [31]:
df1.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [32]:
df2 = pd.read_csv("Housing1.csv")
print(df2.head())

        price    area  bedrooms  bathrooms  stories mainroad guestroom  \
0  13300000.0  7420.0         4        2.0        3      yes        no
1  12250000.0  8960.0         4        4.0        4      yes       NaN
2         NaN  9960.0         3        NaN        2      yes        no
3  12215000.0     NaN         4        2.0        2      yes        no
4  11410000.0  7420.0         4        1.0        2      yes       yes

  basement hotwaterheating airconditioning  parking prefarea furnishingstatus
0       no              no             yes        2      yes        furnished
1       no              no             yes        3       no              NaN
2      yes              no              no        2      yes   semi-furnished
3      yes              no             yes        3      yes        furnished
4      yes              no             yes        2       no        furnished

In [33]:
df2.dropna(inplace=True)
df2.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000.0,7420.0,4,2.0,3,yes,no,no,no,yes,2,yes,furnished
4,11410000.0,7420.0,4,1.0,2,yes,yes,yes,no,yes,2,no,furnished
5,10850000.0,7500.0,3,3.0,1,yes,no,yes,no,yes,2,yes,semi-furnished
6,10150000.0,8580.0,4,3.0,4,yes,no,no,no,yes,2,yes,semi-furnished
7,10150000.0,16200.0,5,3.0,2,yes,no,no,no,no,0,no,unfurnished

In [34]:
df2["price"].head(5)

0    13300000.0
4    11410000.0
5    10850000.0
6    10150000.0
7    10150000.0
Name: price, dtype: float64

In [35]:
df2.info()

<class 'pandas.DataFrame'>
Index: 542 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             542 non-null    float64
 1   area              542 non-null    float64
 2   bedrooms          542 non-null    int64
 3   bathrooms         542 non-null    float64
 4   stories           542 non-null    int64
 5   mainroad          542 non-null    str
 6   guestroom         542 non-null    str
 7   basement          542 non-null    str
 8   hotwaterheating   542 non-null    str
 9   airconditioning   542 non-null    str
 10  parking           542 non-null    int64
 11  prefarea          542 non-null    str
 12  furnishingstatus  542 non-null    str
dtypes: float64(3), int64(3), str(7)
memory usage: 59.3 KB

In [36]:
df2["price"].head(15)

0     13300000.0
4     11410000.0
5     10850000.0
6     10150000.0
7     10150000.0
8      9870000.0
9      9800000.0
10     9800000.0
11     9681000.0
12     9310000.0
13     9240000.0
14     9240000.0
15     9100000.0
16     9100000.0
17     8960000.0
Name: price, dtype: float64

In [39]:
df2 = pd.read_csv("Housing.csv", nrows=50)
print(df2)

       price   area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0   13300000   7420         4          2        3      yes        no       no
1   12250000   8960         4          4        4      yes        no       no
2   12250000   9960         3          2        2      yes        no      yes
3   12215000   7500         4          2        2      yes        no      yes
4   11410000   7420         4          1        2      yes       yes      yes
5   10850000   7500         3          3        1      yes        no      yes
6   10150000   8580         4          3        4      yes        no       no
7   10150000  16200         5          3        2      yes        no       no
8    9870000   8100         4          1        2      yes       yes      yes
9    9800000   5750         3          2        4      yes       yes       no
10   9800000  13200         3          1        2      yes        no      yes
11   9681000   6000         4          3        2      yes       yes      yes
12   9310000   6550         4          2        2      yes        no       no
13   9240000   3500         4          2        2      yes        no       no
14   9240000   7800         3          2        2      yes        no       no
15   9100000   6000         4          1        2      yes        no      yes
16   9100000   6600         4          2        2      yes       yes      yes
17   8960000   8500         3          2        4      yes        no       no
18   8890000   4600         3          2        2      yes       yes       no
19   8855000   6420         3          2        2      yes        no       no
20   8750000   4320         3          1        2      yes        no      yes
21   8680000   7155         3          2        1      yes       yes      yes
22   8645000   8050         3          1        1      yes       yes      yes
23   8645000   4560         3          2        2      yes       yes      yes
24   8575000   8800         3          2        2      yes        no       no
25   8540000   6540         4          2        2      yes       yes      yes
26   8463000   6000         3          2        4      yes       yes      yes
27   8400000   8875         3          1        1      yes        no       no
28   8400000   7950         5          2        2      yes        no      yes
29   8400000   5500         4          2        2      yes        no      yes
30   8400000   7475         3          2        4      yes        no       no
31   8400000   7000         3          1        4      yes        no       no
32   8295000   4880         4          2        2      yes        no       no
33   8190000   5960         3          3        2      yes       yes      yes
34   8120000   6840         5          1        2      yes       yes      yes
35   8080940   7000         3          2        4      yes        no       no
36   8043000   7482         3          2        3      yes        no       no
37   7980000   9000         4          2        4      yes        no       no
38   7962500   6000         3          1        4      yes       yes       no
39   7910000   6000         4          2        4      yes        no       no
40   7875000   6550         3          1        2      yes        no      yes
41   7840000   6360         3          2        4      yes        no       no
42   7700000   6480         3          2        4      yes        no       no
43   7700000   6000         4          2        4      yes        no       no
44   7560000   6000         4          2        4      yes        no       no
45   7560000   6000         3          2        3      yes        no       no
46   7525000   6000         3          2        4      yes        no       no
47   7490000   6600         3          1        4      yes        no       no
48   7455000   4300         3          2        2      yes        no      yes
49   7420000   7440         3          2        1      yes       yes      yes

   hotwaterheating airconditioning  parking prefarea furnishingstatus
0               no             yes        2      yes        furnished
1               no             yes        3       no        furnished
2               no              no        2      yes   semi-furnished
3               no             yes        3      yes        furnished
4               no             yes        2       no        furnished
5               no             yes        2      yes   semi-furnished
6               no             yes        2      yes   semi-furnished
7               no              no        0       no      unfurnished
8               no             yes        2      yes        furnished
9               no             yes        1      yes      unfurnished
10              no             yes        2      yes        furnished
11             yes              no        2       no   semi-furnished
12              no             yes        1      yes   semi-furnished
13             yes              no        2       no        furnished
14              no              no        0      yes   semi-furnished
15              no              no        2       no   semi-furnished
16              no             yes        1      yes      unfurnished
17              no             yes        2       no        furnished
18              no             yes        2       no        furnished
19              no             yes        1      yes   semi-furnished
20             yes              no        2       no   semi-furnished
21              no             yes        2       no      unfurnished
22              no             yes        1       no        furnished
23              no             yes        1       no        furnished
24              no             yes        2       no        furnished
25              no             yes        2      yes        furnished
26              no             yes        0      yes   semi-furnished
27              no              no        1       no   semi-furnished
28             yes              no        2       no      unfurnished
29              no             yes        1      yes   semi-furnished
30              no             yes        2       no      unfurnished
31              no             yes        2       no   semi-furnished
32              no             yes        1      yes        furnished
33              no              no        1       no      unfurnished
34              no             yes        1       no        furnished
35              no             yes        2       no        furnished
36             yes              no        1      yes        furnished
37              no             yes        2       no        furnished
38              no             yes        2       no      unfurnished
39              no             yes        1       no   semi-furnished
40              no             yes        0      yes        furnished
41              no             yes        0      yes        furnished
42              no             yes        2       no      unfurnished
43              no              no        2       no   semi-furnished
44              no             yes        1       no        furnished
45              no             yes        0       no   semi-furnished
46              no             yes        1       no        furnished
47              no             yes        3      yes        furnished
48              no              no        1       no      unfurnished
49              no             yes        0      yes   semi-furnished

In [40]:
print(df2["price"].head(5) , df2["bedrooms"].head(5))

0    13300000
1    12250000
2    12250000
3    12215000
4    11410000
Name: price, dtype: int64 0    4
1    4
2    3
3    4
4    4
Name: bedrooms, dtype: int64

In [42]:
df2.iloc[1]

price                12250000
area                     8960
bedrooms                    4
bathrooms                   4
stories                     4
mainroad                  yes
guestroom                  no
basement                   no
hotwaterheating            no
airconditioning           yes
parking                     3
prefarea                   no
furnishingstatus    furnished
Name: 1, dtype: object

In [44]:
df2.iloc[100: 110]

Empty DataFrame
Columns: [price, area, bedrooms, bathrooms, stories, mainroad, guestroom, basement, hotwaterheating, airconditioning, parking, prefarea, furnishingstatus]
Index: []